name: 'Branch sync action'
description: 'GitHub action to automatically create PR to sync two branch, for all our crazy pipeline needs'
author: 'King Li'
inputs:
  source-branch:
    required: true
  target-branch:
    required: true
  token:
    required: true
  title:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
